float64 pose_x
float64 pose_y
float64 search_distance
float64 minimum_best_response 
bool do_relocalization 

---
float64 best_response
float64 relocated_x
float64 relocated_y
float64 relocated_yaw
string message
bool success



